// Code generated by services/scripts/generate-kysely-tenant-types.ts. DO NOT EDIT.
//
// Every published tenant relation as data: table names and view names.
//
// Source of truth: REMOTE_TABLES / REMOTE_VIEWS in
// services/libs/database/src/initTablesRemote.ts. Regenerate from services/ with:
//   deno run -A --env-file=.env.dev-ports.local scripts/generate-kysely-tenant-types.ts
//
// A drift gate in pg-kysely-tenant/tests/integration/ fails if this file is stale.

/**
 * Every tenant table this package publishes, sorted.
 *
 * With `VIEW_NAMES` this is the whole of `keyof DB`: the two lists are
 * disjoint, and together they name every relation the published types describe.
 * They stay apart because the distinction is part of the contract — views are
 * the stable surface, raw tables may change with notice. A caller who wants one
 * flat list writes `[...TABLE_NAMES, ...VIEW_NAMES]`; a caller handed a flat
 * list cannot recover the split.
 *
 * What these are for: `DB` names every relation Databrill can provision, and
 * any one workspace holds a subset, so a name type-checking is not evidence the
 * relation is there. Diff these lists against your own schema to find out what
 * you actually have.
 *
 * The `as const` does two things here. Without it the declared type is
 * `string[]`, so a consumer could mutate an array the whole package shares —
 * `TABLE_NAMES.push("nope")` would type-check. With it every element type is a
 * string literal, so `new Set<keyof DB>(TABLE_NAMES)` and
 * `db.selectFrom(TABLE_NAMES[0])` compile with no cast, which is the point of
 * the export: the caller's next move is to compare these names against their
 * workspace and hand the survivors to `selectFrom()`.
 */
export const TABLE_NAMES = [
	"amazon_browse_node",
	"amazon_browse_node_attribute",
	"amazon_browse_node_query",
	"amazon_country",
	"amazon_marketplace",
	"amazon_merchant",
	"amazon_product_type_keyword",
	"amazon_store",
	"amzadapi_eligibility_v1__program",
	"amzadapi_exports_v1__ad",
	"amzadapi_exports_v1__adgroup",
	"amzadapi_exports_v1__campaign",
	"amzadapi_exports_v1__target",
	"amzadapi_reports_v1__product01__byDay",
	"amzadapi_reports_v1__search_asin_placement__byDay",
	"amzagg_profit__orderItem",
	"amzagg_profit__orderItemProjectionState",
	"amzfact_fnsku_fbaInventory",
	"amzfact_ledger_build",
	"amzfact_ledger_item",
	"amzfact_ledger_posting",
	"amzfact_ledger_transaction",
	"amzfact_sku_identity",
	"amzms_v1__adgroups",
	"amzms_v1__ads",
	"amzms_v1__budget_usage",
	"amzms_v1__campaigns",
	"amzms_v1__sb_clickstream",
	"amzms_v1__sb_conversion",
	"amzms_v1__sb_rich_media",
	"amzms_v1__sb_traffic",
	"amzms_v1__sd_conversion",
	"amzms_v1__sd_traffic",
	"amzms_v1__sp_conversion",
	"amzms_v1__sp_traffic",
	"amzms_v1__targets",
	"amzop_latest__byStoreAsin",
	"amzreport_ALL_ORDERS",
	"amzreport_COUPON_PERFORMANCE",
	"amzreport_FBA_CUSTOMER_RETURNS",
	"amzreport_FBA_FEE_PREVIEW",
	"amzreport_FBA_INBOUND_NONCOMPLIANCE",
	"amzreport_FBA_INVENTORY_PLANNING",
	"amzreport_FBA_REIMBURSEMENTS",
	"amzreport_FBA_REMOVAL_ORDER_DETAIL",
	"amzreport_FBA_REMOVAL_SHIPMENT_DETAIL",
	"amzreport_FBA_STORAGE_FEE",
	"amzreport_LEDGER_DETAIL",
	"amzreport_LEDGER_SUMMARY",
	"amzreport_MERCHANT_LISTINGS_ALL",
	"amzreport_OPEN_LISTINGS",
	"amzreport_PROMOTION_PERFORMANCE",
	"amzreport_SALES_AND_TRAFFIC__skuByDay",
	"amzreport_SALES_AND_TRAFFIC__store",
	"amzreport_SEARCH_CATALOG_PERFORMANCE",
	"amzreport_SEARCH_QUERY_PERFORMANCE",
	"amzreport_SETTLEMENT_V2",
	"amzreport_SETTLEMENT_V2__summary",
	"amzspapi_awd_v2024__InboundOrder",
	"amzspapi_awd_v2024__InboundShipment",
	"amzspapi_awd_v2024__InboundShipmentSkuQuantity",
	"amzspapi_awd_v2024__Inventory",
	"amzspapi_awd_v2024__ReplenishmentOrder",
	"amzspapi_awd_v2024__ReplenishmentOrderProduct",
	"amzspapi_awd_v2024__ReplenishmentOutboundShipment",
	"amzspapi_catalog_items_v20220401__catalogitem",
	"amzspapi_catalog_items_v20220401__itemattributes",
	"amzspapi_catalog_items_v20220401__itemattributes_lang",
	"amzspapi_catalog_items_v20220401__itemimages",
	"amzspapi_fbaInbound_v0__ShipmentItem",
	"amzspapi_fbaInbound_v2024__InboundPlan",
	"amzspapi_fbaInbound_v2024__Shipment",
	"amzspapi_fbaInbound_v2024__ShipmentItem",
	"amzspapi_fbaInventory_v1__InventorySummary",
	"amzspapi_finances_v20240619__Transaction",
	"amzspapi_finances_v20240619__TransactionItemProjectionState",
	"amzspapi_finances_v20240619__TransactionItemSummary",
	"amzspapi_orders_v0__Order",
	"amzspapi_orders_v0__OrderItem",
	"amzspapi_searchCatalogItems_v2020__asin",
	"amzspapi_searchCatalogItems_v2020__rank",
	"amzspapi_searchCatalogItems_v2020__scrape",
	"amzspapi_searchCatalogItems_v2020__target",
	"amzspapi_sellers_v1__account",
	"amzspapi_sellers_v1__marketplace",
	"amzspapi_sellers_v1__marketplaceParticipation",
	"amzspstream_ACCOUNT_STATUS_CHANGED",
	"amzspstream_ANY_OFFER_CHANGED",
	"amzspstream_B2B_ANY_OFFER_CHANGED",
	"amzspstream_DETAIL_PAGE_TRAFFIC_EVENT",
	"amzspstream_FBA_INVENTORY_AVAILABILITY_CHANGES",
	"amzspstream_FEED_PROCESSING_FINISHED",
	"amzspstream_FEE_PROMOTION",
	"amzspstream_FULFILLMENT_ORDER_STATUS",
	"amzspstream_ORDER_CHANGE",
	"amzspstream_PRICING_HEALTH",
	"amzspstream_REPORT_PROCESSING_FINISHED",
	"brand_config_amazon_asin",
	"brand_config_amazon_attributes",
	"brand_config_amazon_family",
	"brand_config_business_attributes",
	"brand_config_ontology_category",
	"brand_config_ontology_metadata",
	"brand_config_ontology_variant",
	"databrill_schema_version",
	"fx_ecb_rate_history",
	"fx_ecb_rate_latest",
	"shopify_customers_v1__Customer",
	"shopify_discounts_v1__Discount",
	"shopify_discounts_v1__DiscountRedeemCode",
	"shopify_inventory_v1__InventoryLevel",
	"shopify_locations_v1__Location",
	"shopify_orders_v1__Order",
	"shopify_orders_v1__OrderLineItem",
	"shopify_products_v1__Product",
	"shopify_products_v1__ProductVariant",
	"shopify_reports_v1__SalesDaily",
	"shopify_reports_v1__SessionsDaily",
	"shopify_shop_v1__Shop",
	"tfl_asns_v1__Asn",
	"tfl_asns_v1__AsnItem",
	"tfl_inventorySummary_v1__ProductWarehouse",
	"tfl_orders_v1__Order",
	"tfl_orders_v1__OrderItem",
	"tfl_otsShipments_v1__OtsShipment",
	"tfl_otsShipments_v1__OtsShipmentItem",
	"tfl_products_v1__Inventory",
	"tfl_products_v1__Sku",
	"tfl_products_v1__SkuProduct",
	"tfl_products_v1__WarehouseInventory",
	"tfl_shipments_v1__Shipment",
	"wmt_account_v3__profile",
	"wmt_inventory_v3__Wfs",
	"wmt_orders_v3__Order",
	"wmt_orders_v3__OrderLine",
] as const;

/**
 * Every tenant view this package publishes, sorted.
 *
 * The other half of `keyof DB`, and the half to prefer: a view is Databrill's
 * way of keeping a stable shape in front of a schema that evolves. Same
 * `as const` reasoning as `TABLE_NAMES` above, for the same two reasons.
 */
export const VIEW_NAMES = [
	"amazon_ads_ad",
	"amazon_ads_adgroup",
	"amazon_ads_campaign",
	"amazon_ads_target",
	"amazon_fba_inventory_summary",
	"amazon_listing_all",
	"amazon_listing_open",
	"amazon_orders_by_day_and_sku",
	"amazon_sales_and_traffic",
	"brand_ontology_amazon_asin",
	"brand_ontology_amazon_family",
	"brand_ontology_category",
	"brand_ontology_variant",
] as const;
