// Code generated by services/scripts/generate-kysely-tenant-types.ts. DO NOT EDIT.
//
// The schema contract this package was generated against.
//
// Source of truth: REMOTE_TABLES / REMOTE_VIEWS in
// services/libs/database/src/initTablesRemote.ts. Regenerate from services/ with:
//   deno run -A --env-file=.env.dev-ports.local scripts/generate-kysely-tenant-types.ts
//
// A drift gate in pg-kysely-tenant/tests/integration/ fails if this file is stale.

/**
 * The tenant schema contract version this package publishes.
 *
 * Compared against the version recorded in the connected database by
 * `checkSchemaCompatibility()`. Canonically defined in
 * `services/libs/database/src/tenantSchemaVersion.ts`.
 *
 * This is NOT the package version. The package also ships fixes no
 * database can observe, so its patch slot runs ahead; this constant
 * only moves when the schema does.
 */
export const SCHEMA_VERSION: string = "0.1.5";

/**
 * SHA-256 of the generated `db.ts`, for identifying exactly which generated
 * surface a build carries. Informational: compatibility is decided on
 * `SCHEMA_VERSION`, because a database cannot know this hash.
 */
export const SCHEMA_HASH: string = "897fe329b39be5c86231fd5e4bd43a4670495ca0363fa560e77cef483b237c10";
