// Code generated by services/scripts/generate-kysely-tenant-types.ts. DO NOT EDIT.
//
// The schema contract this package was generated against.
//
// Source of truth: REMOTE_TABLES / REMOTE_VIEWS in
// services/libs/database/src/initTablesRemote.ts. Regenerate from services/ with:
//   deno run -A --env-file=.env.dev-ports.local scripts/generate-kysely-tenant-types.ts
//
// A drift gate in pg-kysely-tenant/tests/integration/ fails if this file is stale.

/**
 * The tenant schema contract version this package publishes.
 *
 * Compared against the version recorded in the connected database by
 * `checkSchemaCompatibility()`. Canonically defined in
 * `services/libs/database/src/tenantSchemaVersion.ts`.
 *
 * This is NOT the package version, though the two share their leading two
 * components. The package also ships fixes no database can observe, so its
 * patch slot runs ahead; this constant only moves when the schema does.
 */
export const SCHEMA_VERSION: string = "0.1.0";

/**
 * SHA-256 of the generated `db.ts`, for identifying exactly which generated
 * surface a build carries. Informational: compatibility is decided on
 * `SCHEMA_VERSION`, because a database cannot know this hash.
 */
export const SCHEMA_HASH: string = "0c9e163ca3a07bc3837f25c84a394df1a409c492584c250b520c789e1e5baa0d";
