// Code generated by services/scripts/generate-kysely-tenant-types.ts. DO NOT EDIT.
//
// Tables customers may write, derived from `supabaseRlsMode: "readwrite"`.
//
// Source of truth: REMOTE_TABLES / REMOTE_VIEWS in
// services/libs/database/src/initTablesRemote.ts. Regenerate from services/ with:
//   deno run -A --env-file=.env.dev-ports.local scripts/generate-kysely-tenant-types.ts
//
// A drift gate in pg-kysely-tenant/tests/integration/ fails if this file is stale.

import type { DB } from "./db.ts";

/** Every tenant table a customer role is intended to be able to write. */
export const WRITABLE_TABLE_NAMES = [
	"brand_config_amazon_asin",
	"brand_config_amazon_attributes",
	"brand_config_amazon_family",
	"brand_config_business_attributes",
	"brand_config_ontology_category",
	"brand_config_ontology_metadata",
	"brand_config_ontology_variant",
] as const;

/** The name of a customer-writable tenant table. */
export type WritableTableName = typeof WRITABLE_TABLE_NAMES[number];

/**
 * The write surface: the readable schema narrowed to the writable tables.
 *
 * This is a compile-time affordance, not a security boundary. The enforceable
 * boundary is the grants held by the connecting database role.
 */
export type WritableDB = Pick<DB, WritableTableName>;
