// Code generated by services/scripts/generate-kysely-tenant-types.ts. DO NOT EDIT.
//
// Tables customers may write, derived from `supabaseRlsMode: "readwrite"`.
//
// Source of truth: REMOTE_TABLES / REMOTE_VIEWS in
// services/libs/database/src/initTablesRemote.ts. Regenerate from services/ with:
//   deno run -A --env-file=.env.dev-ports.local scripts/generate-kysely-tenant-types.ts
//
// A drift check in pg-kysely-tenant/tests/integration/ fails if this file is stale.

/**
 * Every tenant table a customer role is intended to be able to write.
 *
 * The `as const` is required across a file boundary: `WritableDB.ts`
 * derives `WritableTableName` as `typeof WRITABLE_TABLE_NAMES[number]`, and
 * without it that widens to `string` and `WritableDB` silently becomes
 * `Pick<DB, string>` — every table writable, with no error anywhere.
 */
export const WRITABLE_TABLE_NAMES = [
	"brand_config_amazon_asin",
	"brand_config_amazon_attributes",
	"brand_config_amazon_family",
	"brand_config_business_attributes",
	"brand_config_ontology_category",
	"brand_config_ontology_metadata",
	"brand_config_ontology_variant",
] as const;
